### PR TITLE
Update skellies.py

### PR DESCRIPTION
**Pull request by b0llull0s**
adding banner

### CODE REVIEW

**Review by k0yaan1sq4tsi — CHANGES_REQUESTED** [review]
Awesome! Can you add color style also?

**Review by b0llull0s — COMMENTED** [review]
I added what you told me

**Review by k0yaan1sq4tsi — CHANGES_REQUESTED** [review]
Awesome! But can you please delete your name on it!

**Review by b0llull0s — COMMENTED** [review]
Done

**Review by k0yaan1sq4tsi — APPROVED** [review]

**Pull request merged**
